version: '3.7'
services: 
    weather-backend:
        container_name: weather-backend
        build: 
            context: ./app/
            dockerfile: Dockerfile
        ports: 
            - "5000:5000"
        restart: always
    weather-app:
        stdin_open: true
        depends_on: 
            - weather-backend
        container_name: weather-app
        build: 
            context: ./ui/
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        restart: always
        