

export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR';
export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST';

export const ADD_WEATHER = 'ADD_WEATHER';
export const ADD_WEATHER_SUCCESS = 'ADD_WEATHER_SUCCESS';
export const ADD_WEATHER_ERROR = 'ADD_WEATHER_ERROR';
export const ADD_WEATHER_REQUEST = 'ADD_WEATHER_REQUEST';

export const CLEAR_FAVORITE_WEATHER = 'CLEAR_FAVORITE_WEATHER';
export const REMOVE_WEATHER = 'REMOVE_WEATHER';
export const REMOVE_WEATHER_SUCCESS = 'REMOVE_WEATHER_SUCCESS';
export const REMOVE_WEATHER_ERROR = 'REMOVE_WEATHER_ERROR';
export const REMOVE_WEATHER_REQUEST = 'REMOVE_WEATHER_REQUEST';

export const GET_FAVORITE_WEATHER = 'GET_FAVORITE_WEATHER';
export const GET_FAVORITE_WEATHER_SUCCESS = 'GET_FAVORITE_WEATHER_SUCCESS';
export const GET_FAVORITE_WEATHER_ERROR = 'GET_FAVORITE_WEATHER_ERROR';
export const GET_FAVORITE_WEATHER_REQUEST = 'GET_FAVORITE_WEATHER_REQUEST';